TEAMS = {
    "Ari": "D-backs",
    "Atl": "Braves",
    "Bal": "Orioles",
    "Bos": "Red Sox",
    "ChC": "Cubs",
    "ChW": "White Sox",
    "Cin": "Reds",
    "Cle": "Guardians",
    "Col": "Rockies",
    "Det": "Tigers",
    "Hou": "Astros", 
    "KC": "Royals",
    "LAD": "Dodgers",
    "LAA": "Angels",
    "Mia": "Marlins",
    "Mil": "Brewers",
    "Min": "Twins",
    "NYM": "Mets",
    "NYY": "Yankees",
    "Oak": "A's",
    "Phi": "Phillies",
    "Pit": "Pirates",
    "SD": "Padres",
    "Sea": "Mariners",
    "SF": "Giants",
    "StL": "Cardinals",
    "TB": "Rays",
    "Tex": " Rangers",
    "Tor": "Blue Jays",
    "Wsh": "Nationals",
}