TEAMS = {
    "Ari": "Arizona Diamondbacks",
    "Atl": "Atlanta Braves",
    "Bal": "Baltimore Orioles",
    "Bos": "Boston Red Sox",
    "ChC": "Chicago Cubs",
    "ChW": "Chicago White Sox",
    "Cin": "Cincinnati Reds",
    "Cle": "Cleaveland Guardians",
    "Col": "Colorado Rockies",
    "Det": "Detroit Tigers",
    "Hou": "Houston Astros", 
    "KC": "Kansas City Royals",
    "LAD": "Los Angeles Dodgers",
    "LAA": "Los Angeles Angels",
    "Mia": "Miami Marlins",
    "Mil": "Millwaukee Brewers",
    "Min": "Minnesota Twins",
    "NYM": "New York Mets",
    "NYY": "New York Yankees",
    "Oak": "Oakland Athletics",
    "Phi": "Philadelphia Phillies",
    "Pit": "Pittsburgh Pirates",
    "SD": "San Diego Padres",
    "Sea": "Seattle Mariners",
    "SF": "San Francisco Giants",
    "StL": "St. Louis Cardinals",
    "TB": "Tampa Bay Rays",
    "Tex": "Texas Rangers",
    "Tor": "Toronto Blue Jays",
    "Wsh": "Washington Nationals",
}