TEAMS = {
    "Ari": "D-backs",
    "Atl": "Braves",
    "Bal": "Orioles",
    "Bos": "Red Sox",
    "ChC": "Cubs",
    "ChW": "White Sox",
    "Cin": "Reds",
    "Cle": "Guardians",
    "Col": "Rockies",
    "Det": "Tigers",
    "Hou": "Astros", 
    "KC": "Royals",
    "LAD": "Dodgers",
    "LAA": "Angels",
    "Mia": "Marlins",
    "Mil": "Brewers",
    "Min": "Twins",
    "NYM": "Mets",
    "NYY": "Yankees",
    "Oak": "A's",
    "Phi": "Phillies",
    "Pit": "Pirates",
    "SD": "Padres",
    "Sea": "Mariners",
    "SF": "Giants",
    "StL": "Cardinals",
    "TB": "Rays",
    "Tex": "Rangers",
    "Tor": "Blue Jays",
    "Wsh": "Nationals",
}

FULL_TO_PARTIAL_NAME = {
"Arizona Diamondbacks": "D-backs",
"Atlanta Braves": "Braves",
"Baltimore Orioles": "Orioles",
"Boston Red Sox": "Red Sox",
"Chicago Cubs": "Cubs",
"Chicago White Sox": "White Sox",
"Cincinnati Reds": "Reds",
"Cleaveland Guardians": "Guardians",
"Colorado Rockies": "Rockies",
"Detroit Tigers": "Tigers",
"Houston Astros": "Astros", 
"Kansas City Royals": "Royals",
"Los Angeles Dodgers": "Dodgers",
"Los Angeles Angels": "Angels",
"Miami Marlins": "Marlins",
"Milwaukee Brewers": "Brewers",
"Minnesota Twins": "Twins",
"New York Mets": "Mets",
"New York Yankees": "Yankees",
"Oakland Athletics": "A's",
"Philadelphia Phillies": "Phillies",
"Pittsburgh Pirates": "Pirates",
"San Diego Padres": "Padres",
"Seattle Mariners": "Mariners",
"San Francisco Giants": "Giants",
"St. Louis Cardinals": "Cardinals",
"Tampa Bay Rays": "Rays",
"Texas Rangers": "Rangers",
"Toronto Blue Jays": "Blue Jays",
"Washington Nationals": "Nationals",
}